
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://dttonqyqzmxcsitijwuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0dG9ucXlxem14Y3NpdGlqd3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTc1NzUsImV4cCI6MjA3NDE5MzU3NX0.qtr-vMIfiwu-sf7BieXZgX2MWYmmZxVB8wwebzEkWVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define RPC function parameter and return types
interface RpcFunctions {
  verify_user_password: {
    params: { user_id: string; password: string };
    returns: boolean;
  };
  add_custom_user: {
    params: { p_name: string; p_phone: string; p_password: string; p_role?: string };
    returns: { id: string };
  };
  update_user_with_password: {
    params: { p_user_id: string; p_name?: string; p_phone?: string; p_password?: string };
    returns: void;
  };
  send_verification_code: {
    params: { p_phone: string };
    returns: string;
  };
  verify_phone_number: {
    params: { p_phone: string; p_code: string };
    returns: { success: boolean; customer?: unknown; message?: string };
  };
}

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true
    }
  }
);

// Admin client with service_role key (bypasses RLS)
// Use this for admin operations that need elevated permissions
const SUPABASE_SERVICE_ROLE_KEY = import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY;

export const supabaseAdmin = SUPABASE_SERVICE_ROLE_KEY
  ? createClient<Database>(
      SUPABASE_URL,
      SUPABASE_SERVICE_ROLE_KEY,
      {
        auth: {
          persistSession: false,
          autoRefreshToken: false
        }
      }
    )
  : null;
