// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilabjurydougiuvljbjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsYWJqdXJ5ZG91Z2l1dmxqYmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDUxMDEsImV4cCI6MjA1OTAyMTEwMX0.h0aJjj44IjvafiHzIxGox8G4NazgKTnzc86nnzMq-Vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);