
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilabjurydougiuvljbjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsYWJqdXJ5ZG91Z2l1dmxqYmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDUxMDEsImV4cCI6MjA1OTAyMTEwMX0.h0aJjj44IjvafiHzIxGox8G4NazgKTnzc86nnzMq-Vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom type that extends the Database type with our custom RPC functions
type CustomSupabaseClient = ReturnType<typeof createClient<Database>> & {
  rpc: <T extends "verify_user_password" | "add_custom_user" | "update_user_with_password">(
    fn: T,
    params: Record<string, any>
  ) => any;
};

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true
    }
  }
) as CustomSupabaseClient;
